require: rubocop-rspec

inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.5.3
  TargetRailsVersion: 5.2.1
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'app/javascript/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: rails

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 7
  Exclude:
    - 'app/controllers/api/v1/groups_controller.rb'

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 8
  Exclude:
    - 'app/controllers/api/v1/groups_controller.rb'
    - 'app/controllers/concerns/hyacinth/users/cas_authentication_behavior.rb'

Style/BracesAroundHashParameters:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false
