require: rubocop-rspec

inherit_gem:
  rubocop-rails:
    - config/rails.yml

AllCops:
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'app/helpers/**/*'
    - 'app/views/**/*'
    - 'lib/tasks/**/*'

Layout/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Layout/IndentationConsistency:
  EnforcedStyle: rails

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/hyacinth/xml_generator/element.rb'
    - 'app/jobs/process_digital_object_import_job.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/hyacinth/xml_generator/element.rb'
    - 'app/jobs/process_digital_object_import_job.rb'

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Exclude: []
  CountComments: false  # count full line comments?
  Max: 275

Metrics/ModuleLength:
  Exclude: []
  CountComments: false
  Max: 110

Naming/PredicateName:
  Exclude: []

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Exclude: []

Style/LineEndConcatenation:
  Exclude: []

Style/GlobalVars:
  Exclude:
    - 'spec/**/*'

Style/SingleLineBlockParams:
  Enabled: false

Style/ClassVars:
  Exclude: []

Style/SignalException:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

Rails/Output:
  Exclude:
    - 'lib/generators/**/*'
    - 'lib/hyacinth/utils/logger.rb'
    - 'config/deploy.rb'

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/jobs/event_jobs_spec.rb'
    - 'spec/features/**/*'
    - 'spec/views/**/*'
    - 'spec/routing/**/*'
