inherit_gem:
  bixby: bixby_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5.3
  TargetRailsVersion: 5.2.1
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'app/javascript/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'lib/tasks/hyacinth/**/*'

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: rails

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 7
  Exclude:
    - 'app/controllers/api/v1/groups_controller.rb'
    - 'app/models/concerns/digital_object_concerns/save_behavior.rb'

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 8
  Exclude:
    - 'app/controllers/api/v1/groups_controller.rb'
    - 'app/controllers/concerns/hyacinth/users/cas_authentication_behavior.rb'
    - 'app/models/concerns/digital_object_concerns/save_behavior.rb'

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

# Unset these overrides later (when we have time to address them)

Bundler/OrderedGems:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - 'app/models/concerns/digital_object_concerns/save_behavior.rb'
