inherit_gem:
  rubocul: rubocul_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6.4
  TargetRailsVersion: 6.0.2

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true