dist: bionic
language: ruby
cache:
  bundler: true
  npm: true
  yarn: true
  directories:
    - tmp/solr-download

rvm:
  - 2.6.4

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - NODE_VERSION=8
    - NODE_VERSION=10

jdk: 'openjdk8'

addons:
  chrome: stable

before_install:
  - "echo 'gem: --no-document' > ~/.gemrc"
  - gem update --system 3.0.6
  - gem install bundler

before_script:
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install -g yarn
  - npm --version
  - yarn install
