language: ruby
sudo: false
cache:
  bundler: true
  npm: true
  yarn: true
  directories:
    - tmp/solr-download

rvm:
  - 2.5.3
  - 2.6.1

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - NODE_VERSION=8
    - NODE_VERSION=10

jdk: 'openjdk8'

addons:
  chrome: stable

before_install:
  - "echo 'gem: --no-document' > ~/.gemrc"
  - gem update --system
  - gem install bundler

before_script:
  # Set up hyacinth config files like hyacinth.yml and database.yml
  - bundle exec rake hyacinth:setup:config_files
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install -g yarn
  - npm --version
  - yarn install
