dist: bionic
language: ruby
cache: bundler
sudo: false

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

rvm:
  - 2.4.1

jdk: 'openjdk8'

notifications:
  irc: "irc.freenode.org#ldpddev"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
  # Make sure the line below matches the Gemfile.lock bundler version.
  # We could remove the line if we upgraded to Bundler 2, but Rails 4.2.x locks us at Bundler 1.
  - gem install bundler:1.17.3

before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
  - bundle exec rake hyacinth:setup:config_files

script: bundle exec rake hyacinth:ci
