development:
  metadata_storage:
    storage_adapters:
      - type: disk
        default_path: <%= Rails.root.join('tmp', 'development', 'metadata') %>
  resource_storage:
    storage_adapters:
      - type: disk
        default_path: <%= Rails.root.join('tmp', 'development', 'resources') %>
  lock_adapter:
    type: database_entry_lock
    lock_timeout: <%= 1.minute %>
  search_adapter:
    type: solr
    url: http://localhost:8983/hyacinth_development
  preservation_persistence:
    adapters:
      - type: fedora3
        url: http://localhost:8080/fedora
        user: fedoraAdmin
        password: fedoraAdmin
  uri_sevice:
    url: 'https://example.com'
    api_key: 'notasecret'

test:
  metadata_storage:
    adapters:
      - type: disk
        default_path: <%= Rails.root.join('tmp', 'test', 'metadata') %>
  resource_storage:
    adapters:
      - type: disk
        default_path: <%= Rails.root.join('tmp', 'test', 'resources') %>
  lock_adapter:
    type: database_entry_lock
    lock_timeout: <%= 30.seconds %>
  search_adapter:
    type: solr
    url: http://localhost:9983/hyacinth_test
  preservation_persistence:
    adapters:
      - type: fedora3
        url: http://localhost:9080/fedora
        user: fedoraAdmin
        password: fedoraAdmin
  uri_sevice:
    url: 'https://example.com'
    api_key: 'notasecret'
