# Note: startup_wait is a timeout (in seconds), not block/sleep

default: &default
  startup_wait: 120
  java_version: ">= 1.8"
  java_opts:
    - "-XX:MaxPermSize=128m"
    - "-Xmx256m"

development:
  <<: *default
  jetty_port: 8080

test:
  <<: *default
  jetty_port: 9090
