default: &default
  accounts:
    Hyacinth2:
      url: https://foreignhost.org/hyacinth
      user: test@library.columbia.edu
      password: testing
development:
  <<: *default
test:
  <<: *default
